### ISSUE TITLE
Fails on pure functions that are spuriously bound

### ISSUE THREAD

**Issue by webbedspace** [lebab/lebab#105]
Consider this code:
`
var x = function() {
  return 2;
}.bind(this);
`
This incorrectly becomes `const x = () => 2.bind(this);`.

**Comment by nene** [comment]
Thanks for reporting. That's quite an important bug.

**Comment by nene** [comment]
Turns out to be a bug in recast: https://github.com/benjamn/recast/issues/264

Hopefully Recast can fix it soon enough, so we don't have to create a workaround.

**Comment by nene** [comment]
This is now mostly solved by simply removing `.bind(this)` from arrow functions. So the above code becomes:

    const x = () => 2;

The issue still remains when one decides to call some other methods, like:

    x = function(a,b){ return a+b: }.apply(this, [1, 2]);

This should be a fairly rare scenario, so waiting for Recast to fix their bug.

**Comment by mdebbar** [comment]
Hey @nene, you've got a nice project here! And my first contribution would be to fix this long standing bug in Recast :)

**Comment by nene** [comment]
Thanks!
