### ISSUE TITLE
Converting `React.createClass` to `extends React.Component`

### ISSUE THREAD

**Issue by mohebifar** [lebab/lebab#133]
Thanks to @nene's great work, now that lebab supports JSX, I wonder if it would be a good idea to create a new transform that converts this:

``` jsx
const Example = React.createClass({
  render() {
    return <div>Hey</div>;
  }
})
```

to:

``` jsx
class Example extends React.Component {
  render() {
    return <div>Hey</div>;
  }
}
```

The thing is that this is something related to React (or preact). I am not sure if it would be a good idea to have such transformers in lebab.

**Comment by nene** [comment]
This looks like a useful transform to have. It should also consider all the other differences of ES6 classes from `React.createClass`, as documented in [React docs](http://facebook.github.io/react/docs/reusable-components.html#es6-classes):

- No `getInitialState()`, instead a constructor has to be used.
- `propTypes` and `defaultProps` have to be attached separately. A better way would be using future ECMAScript class-properties syntax, but for this we would need some more parser support.
- Event handlers have no autobinding, so we'll need to add `.bind(this)` (probably better than wrapping inside arrow functions).
- No mixins. I guess we'll just need to skip transforming components that use mixins.

Additionally, this transform should not be enabled by default, like other transforms currently are. This relates to another topic that I've been pondering over: #134

**Comment by iosluoyang** [comment]
Hi , there.
I've met the same prob like @mohebifar  , now I want to convert the code like "React.createClass" to the JSX model .(Like class Example extends React.Component  ) .But after looked through all the issues , I cannot find the suitable answer , this question seems to related , so I tried to find the answer as well ,but also failed. 
Actually I dont exactly know about what the author said , Can the lebab solve this prob now ?

Looking for reply , thanks

**Comment by nene** [comment]
Hi @iosluoyang,

Lebab does not do any React/JSX transforms like converting React.createClass to extends React.Component.

The JSX support which @mohebifar referred to is that Lebab no more crashes when it encounters JSX code.

**Comment by nene** [comment]
For now not going to do. Will be concentrating on transforming more of a standard JavaScript syntax.
