### ISSUE TITLE
Use for of loops instead of for in

### ISSUE THREAD

**Issue by mdibaiee** [lebab/lebab#18]
We should probably consider the usage of iterator inside for in loops, in that case we have to use `.entries()` if possible.

**Comment by nene** [comment]
Do I understand correctly that goal of this feature would be to convert the following code:

```js
for (var key in obj) {
    if (obj.hasOwnProperty(key)) {
        var value = obj[key];
        doSomething(key, value);
    }
}
```

to this:

```js
for (const [key, value] in Object.entries(obj)) {
    doSomething(key, value);
}
```

...with the main value of eliminating this extra `if` with `hasOwnProperty()` check.

IMHO a fairly complex transform with fairly small benefit. I'd rather first transform ordinary `for` loops over arrays to `for-of`.

**Comment by nene** [comment]
Closing this old feature proposal. As explained above, it doesn't seem to provide big enough of a benefit. A PR is always welcome, if there really is desire for this.
