### ISSUE TITLE
commonjs transform adds semicolon to import statements

### ISSUE THREAD

**Issue by josephfrazier** [lebab/lebab#195]
For example:

```js
> require("lebab").transform('var m = require("module")', ['commonjs']).code
'import m from "module";'
```

After searching through the existing issues, this sounds similar to https://github.com/lebab/lebab/issues/159

**Comment by nene** [comment]
This is really a problem in Recast library. I've posted an issue about that: https://github.com/benjamn/recast/issues/344

I assume it's something that's not going to be easily fixed.

Are you following a code style of having no semicolons? In that case you could use `eslint` to auto-fix the semicolons that were added by Lebab.

**Comment by josephfrazier** [comment]
Thanks for digging into this! I was experimenting with `lebab` on a project that uses [`standard`](https://github.com/feross/standard) for linting, so I can indeed use `--fix` to remove the semicolons.

**Comment by nene** [comment]
Closing this. If Recast library adds auto-detection of no-semicolons style, then Lebab will adopt the fix. Until then other tools can be used to correct the style.
