### ISSUE TITLE
wrong associations of power function (missing parentheses)

### ISSUE THREAD

**Issue by michaljuris** [lebab/lebab#196]
`Math.pow(x*2, 2)/2`
translates to
`x*2 ** 2/2`
but that's **wrong**, correct expression should be
`(x*2) ** 2/2`

**Comment by nene** [comment]
Thanks for reporting.

My first guess was that it's related to Recast library, which has had a lot of issues with handling of parenthesis, but my first tests show that things are OK. Will have to further investigate.

**Comment by nene** [comment]
Sorry for the lack of feedback on this.

Turns out Recast got the operator precedence wrong. Opened a PR: https://github.com/benjamn/recast/pull/363

Hopefully that will get merged soon and then this issue should get solved.
