### ISSUE TITLE
Wrong transform Arrow function in objects 

### ISSUE THREAD

**Issue by msudgh** [lebab/lebab#198]
I'm trying to use Lebab's Try it tool to transform an object with inner function but it couldn't do that.
Screenshot:
![image](https://cloud.githubusercontent.com/assets/11756815/21111405/a7c462ae-c0b6-11e6-9ab7-c9333c8422b5.png)

it should be **`x: (date) =>`** or even **`x: function(date)`**.

thanks

**Comment by nene** [comment]
Thanks for bug-report.

Released the fix in Lebab 2.6.2

The Lebab try-it page is lagging behind though. Perhaps @mohebifar could do something about that.

**Comment by msudgh** [comment]
Thanks for your speeding of bug fixing :)
