### ISSUE TITLE
unify qoutes

### ISSUE THREAD

**Issue by jimmywarting** [lebab/lebab#204]
I would like it if all quotes could be transformed to single quote If template strings are not necessary and escaping is not necessary 

![skarmavbild 2017-01-03 kl 01 18 24](https://cloud.githubusercontent.com/assets/1148376/21597915/9fc220b2-d152-11e6-97c9-441b0aaf5f49.png)

Another thing that bothers me are that semicolons are being added...

**Comment by nene** [comment]
The problem of added semicolons stems from [Recast](https://github.com/benjamn/recast/) library that Lebab uses to print out the transformed code. A workaround for this is to use [ESLint](http://eslint.org/) to auto-fix the semicolon style.

Regarding quotes, you can again use ESLint to `--fix` [quotes style](http://eslint.org/docs/rules/quotes). I don't see a need to implement such a transform in Lebab.
