### ISSUE TITLE
`multi-var` with comments between variable declarations

### ISSUE THREAD

**Issue by jmiguel-localvox** [lebab/lebab#211]
A code snippet is worth a thousand words so:

with `multi-var` transform

```javascript
var something, // bla bla bla
    whatever; // yatta yatta yatta
```

becomes

```javascript
var // bla bla bla
something; // yatta yatta yatta

var whatever;
```

expected

```javascript
var something; // bla bla bla
var whatever; // yatta yatta yatta
```

Note, the generated code does run, it's just not ideal for refactoring purposes. This issue is not isolated to single line comments. Should this be considered a bug or a feature enhancement?

**Comment by nene** [comment]
It's pretty tricky to preserve these comments correctly. What Lebab actually sees is more like this:

```js
{
    type: "VariableDeclaration",
    comment: "// yatta yatta yatta",
    declarators: [
        { type: "VariableDeclarator", id: "something", comment: "// bla bla bla" },
        { type: "VariableDeclarator", id: "whatever" },
    ]
}
```

This is actually already pretty good as far as comments in abstract syntax trees (AST) go, [Recast](https://github.com/benjamn/recast/) manages to correctly associate the first comment with the first declarator, but it doesn't do well with associating the second comment with the second declarator - instead associating it with the entire declaration.

So when Lebab moves the second declarator to a new declaration node, it cannot tell that there's a comment belonging to it, and so the comment will remain inside the first declaration block. From Lebab perspective this AST is equivalent to:

```js
// bla bla bla
var something, // bla bla bla
    whatever;
```

Therefore I'd say it's more of a bug in Recast. If you really care, you should file a bug to Recast, I've filed quite a lot of subtle issues like this already, and I don't want to bother Ben with all these cases that I know are really hard to get right.
