### ISSUE TITLE
Add code coverage using NYC and integrate with codecov

### ISSUE THREAD

**Issue by addi90** [lebab/lebab#212]
- [x] Add code coverage metrics for `lebab`
- [x] Integrate with `codecov` to push code coverage data to codecov

#### Example:

<img width="711" alt="screen shot 2017-01-19 at 9 33 39 am" src="https://cloud.githubusercontent.com/assets/5351262/22099152/6f599592-de2a-11e6-9107-715d8d09ee4f.png">

Sample Reference: https://github.com/addi90/build-notification-api/blob/master/package.json#L9

**Comment by nene** [comment]
Well, there was some work done with code coverage just recently: https://github.com/lebab/lebab/pull/206

I was planning to fiddle with it, to get it working properly. But haven't found time right now, so @abouthiroppy ended up closing the PR for now. The only thing really needed to do for it is to separate out the system tests from unit tests, and then enable the code coverage only for the latter.

**Comment by abouthiroppy** [comment]
Yep. If you have nice idea, I would like to try it.

**Comment by addi90** [comment]
@nene Sure. I will put some time later today to separate them out and then try running them. My suggestions:
- Use separate npm commands for running unit test and system tests. E.g. `npm run test` and `npm run system-test` 
- Use a name convention like `*.spec.js` or ``*.test.js` for unit test and retain the `*Test.js` for system tests

Let me know what you guys think.

**Comment by abouthiroppy** [comment]
@nene How do you think his idea?

**Comment by addi90** [comment]
Updated the description to add an existing reference

**Comment by nene** [comment]
Rather than use a file-extension, I'd simply move the system tests to separate directory. And then `npm run test` and `nps run system-test` would simply execute tests in corresponding directories.

FYI: there's really just one system test `test/binTest.js`, however I still think a separate directory would serve it better.

**Comment by addi90** [comment]
Wonderful. I would try to move the system test to `system-test` and then create the scripts to run both the tests separately
