### ISSUE TITLE
Use as a build script?

### ISSUE THREAD

**Issue by thednp** [lebab/lebab#217]
I want to be able to build ES6 bundles and I cannot seem to have any success so far, here's my file:

```js
var fs = require('fs');
var path = require('path');
var lebab = require('lebab');
var pack = require('./package.json');
var version = 'v'+pack.version;
var license = pack.license+'-License';

console.log('ES6ify myModule.js ' + version + '..');

// Helper Functions:
function es6(srcPath, writePath) {
   fs.writeFile(writePath,
    ('//myModule.js ' + version + ' | © thednp | ' + srcPath  + ' | ' + license + '\n'
       // + lebab.transform(fs.readFileSync(srcPath)) 
       + lebab.transform(srcPath)
    ) 
  )
  // console.log(lebab.transform(fs.readFile(srcPath)))
}


// ES6ify files
es6('src/module.js', 'src/build.js');
```

As you can see I've tried everything with no success, please anyone have any ideas?

**Comment by thednp** [comment]
If not I am just going to use this in my `package.json` and it works:

```js
  "scripts": {
    "es6": "lebab src/myModule.js -o src/build.js --transform let"
  },
```

**Comment by nene** [comment]
Well, to make `lebab.transform()` work, you'll need to also specify which transforms you'd like to apply:

    lebab.transform('var f = function(){};', ['let', 'arrow']);

See README for details.

However, including Lebab to your build process seems a pretty weird thing to do. Normally people want to work in ES6 and compile their code down to ES5 during build. I'm curious, why would you want to do the opposite? I should also warn you that Lebab is not a fully safe transform tool like Babel, which you could run blindly and expect your code to work exactly like before.

**Comment by thednp** [comment]
> I should also warn you that Lebab is not a fully safe transform tool like Babel, which you could run blindly and expect your code to work exactly like before.

I am still experimenting, trying to learn as much as possible, working on ways to automate alot of the work I used to do with copy/paste & find/replace. SO thanks for your reply and the warning.
