### ISSUE TITLE
util.inherits conversion failed

### ISSUE THREAD

**Issue by GusCaplan** [lebab/lebab#224]
running <https://github.com/mikaelbr/node-notifier> through lebab failed to catch the `EventEmitter.call(this)` and `util.inherits(x, EventEmitter);` in the notification classes

**Comment by nene** [comment]
@GusCaplan, could you be more specific?

- What is the exact input that you're giving to Lebab?
- What is the output Lebab gives you?
- What kind of output are you expecting?

**Comment by GusCaplan** [comment]
input is an es5 class which uses util.inherits to extend eventemitter
output is a es6 class with the util.inherits still in the constructor and such
i was expecting it instead to do `extends EventEmitter` and it says in the readme it should do that

**Comment by GusCaplan** [comment]
input is a pre-es6 function with prototype that uses util.inherits to extend EventEmitter
output is a es6 class with the eventemitter.call still in the constructor and util.inherits
i was expecting it instead to do `extends EventEmitter` and it says in the readme it should do that.

**Comment by nene** [comment]
I suspect you're using an older version of Lebab, or you're using the try-it-live tool, which is outdated as well. @mohebifar, could we update it to run the latest version?

When I try `lebab --transform class toaster.js` I get the following result:

```js
/**
 * Wrapper for the toaster (https://github.com/nels-o/toaster)
 */
var path = require('path');
var notifier = path.resolve(__dirname, '../vendor/snoreToast/SnoreToast.exe');
var utils = require('../lib/utils');
var Balloon = require('./balloon');

var EventEmitter = require('events').EventEmitter;
var util = require('util');

var fallback = void 0;

module.exports = WindowsToaster;

class WindowsToaster extends EventEmitter {
  constructor(options) {
    options = utils.clone(options || {});
    if (!(this instanceof WindowsToaster)) {
      return new WindowsToaster(options);
    }

    this.options = options;

    super();
  }

  notify(options, callback) {
    options = utils.clone(options || {});
    callback = callback || noop;

    if (typeof options === 'string') {
      options = { title: 'node-notifier', message: options };
    }

    if (typeof callback !== 'function') {
      throw new TypeError(
        'The second argument must be a function callback. You have passed ' +
          typeof fn
      );
    }

    var actionJackedCallback = utils.actionJackerDecorator(
      this,
      options,
      function cb(err, data) {
        // Needs to filter out timeout. Not an actual error.
        if (err && hasText(data, timeoutMessage)) {
          return callback(null, data);
        }
        callback(err, data);
      },
      function mapper(data) {
        if (hasText(data, successMessage)) {
          return 'click';
        }
        if (hasText(data, timeoutMessage)) {
          return 'timeout';
        }
        return false;
      }
    );

    options.title = options.title || 'Node Notification:';
    if (
      typeof options.message === 'undefined' &&
        typeof options.close === 'undefined'
    ) {
      callback(new Error('Message or ID to close is required.'));
      return this;
    }

    if (!utils.isWin8() && !!this.options.withFallback) {
      fallback = fallback || new Balloon(this.options);
      return fallback.notify(options, callback);
    }

    options = utils.mapToWin8(options);
    var argsList = utils.constructArgumentList(options, {
      explicitTrue: true,
      wrapper: '',
      keepNewlines: true,
      noEscape: true
    });
    utils.fileCommand(
      this.options.customPath || notifier,
      argsList,
      actionJackedCallback
    );
    return this;
  }
}

function noop() {
}

var timeoutMessage = 'the toast has timed out';
var successMessage = 'user clicked on the toast';

function hasText(str, txt) {
  return str && str.indexOf(txt) !== -1;
}
```

This isn't really correct as `super()` should not be called after using `this` in constructor (issue #186), plus the fact that `WindowsToaster` class can't be referenced before it's defined.

**Comment by GusCaplan** [comment]
i was using the try-it-live *blushes*. But in any event, the issues in the above would keep the code from working anyway, so many that is what this issue should track at this point.

**Comment by nene** [comment]
Created a separate issue for the referencing class before defined issue: #225.
