### ISSUE TITLE
Template transform removes comments in ternaries

### ISSUE THREAD

**Issue by josephfrazier** [lebab/lebab#229]
On https://lebab.io/try-it: 

Input:

```js
function f (outerCapNames, localCapIndex, outerCapsMap, $4) {
	return outerCapNames[localCapIndex] ?
		// Need to preserve the backreference name in case using flag `n`
		'\\k<' + outerCapNames[localCapIndex] + '>' :
		'\\' + outerCapsMap[+$4];
}
```

Output:

```js
function f (outerCapNames, localCapIndex, outerCapsMap, $4) {
	return outerCapNames[localCapIndex] ?
		`\\k<${outerCapNames[localCapIndex]}>` :
		`\\${outerCapsMap[+$4]}`;
}
```

Note that the following comment is missing in the output:

```js
// Need to preserve the backreference name in case using flag `n`
```

Demo: https://runkit.com/josephfrazier/lebab-template-transform-removes-comments/1.0.0

**Comment by nene** [comment]
Thanks for reporting. I've been away for a while... looks like a bug. Will find time to take a look.

**Comment by nene** [comment]
Thanks, that's a good start for the fix. It's now preserving comments that are before the expression that gets turned into template string, but still discards comments inside an expression, like this:

```js
var foo =
    // First comment
    "Firstname: " + fname +
    // Second comment
    " Lastname: " + lname;
```

**Comment by nene** [comment]
With the last PR merged, I think it's good now.
