### ISSUE TITLE
Arrow transform reorders comments

### ISSUE THREAD

**Issue by josephfrazier** [lebab/lebab#230]
Demo: https://runkit.com/josephfrazier/lebab-arrow-transform-reorders-comments/1.0.0

Input:

```js
XRegExp.isRegExp = function(value) {
    return toString.call(value) === '[object RegExp]';
    //return isType(value, 'RegExp');
}
```

Output:

```js
XRegExp.isRegExp = value => //return isType(value, 'RegExp');
toString.call(value) === '[object RegExp]'
```

Ideally, the comment would go after the return value, like this:

```js
XRegExp.isRegExp = value => toString.call(value) === '[object RegExp]' //return isType(value, 'RegExp');
```

**Comment by nene** [comment]
Thanks for reporting.

That's kind of tricky to solve. The main goal in Lebab is to just preserve the comments. The actual job of rendering them to output them is done by Recast library. Figuring out the most natural place is pretty hard job. If you really think it's important, you might want to file that bug to Recast, but I don't think it's a hight priority issue for Recast to tackle either.

Sorry. Won't be putting any effort into fixing this.

**Comment by josephfrazier** [comment]
No problem, I definitely appreciate the difficulty of placing comments. Just wanted to make sure the issue was "on the record". Thanks for all your work on lebab!
