### ISSUE TITLE
defining class

### ISSUE THREAD

**Issue by cybermerlin** [lebab/lebab#232]
var Base = function (cfg){};
(function(){
Base.prototype = {
  name: 'asdf',
  st: function(){},
  constructor: function(){}
};
Base.ss = Base.prototype.st;
Base.st = Base.prototype.st;
})();
var bb = new Base();

**Comment by nene** [comment]
Please describe the problem that you're having, don't just post arbitrary code snippets.

**Comment by cybermerlin** [comment]
result is not true

```js
const Base = cfg => {};
((() => {
Base.prototype = {
name: 'asdf',
st() {},
constructor() {}
};
Base.ss = Base.prototype.st;
Base.st = Base.prototype.st;
}))();
const bb = new Base();
```

**Comment by nene** [comment]
Sorry... but you have to try harder.
