### ISSUE TITLE
add options to try-it

### ISSUE THREAD

**Issue by kofifus** [lebab/lebab#234]
First let me say that lebab is amazing and extremely useful !

I wanted to ask if the try-it demo can have a togles for the various features, this will make it very handy to lebab snippets on the fly.

Thanks

**Comment by nene** [comment]
Unfortunately I'm personally not maintaining the try-it demo and the lebab.io site.

@mohebifar, could we consider updating the site?

**Comment by nene** [comment]
Solved by new live-demo site: #253
