### ISSUE TITLE
Transformations with valid class-level instance and static field declarations

### ISSUE THREAD

**Issue by somombo** [lebab/lebab#237]
> ### TL;DR 
> * **Potential Bug** : 
There is a fatal error when you try to run `class Foo {  bar = "hello"; }` through lebab (with any transform).  
> * **Feature Request**: 
`function Foo() { this.bar = "hello"; }` and `function Foo() {}; Foo.prototype.bar = "hello";` 
(and iife variations) 
should both result in `class Foo {  bar = "hello"; }` when run through lebab

The following shows class level instance and static field declarations that are perfectly valid ES6/7,
and are the kind of thing that's actually often _required_ in typescript.

#### ES6/7 Snippet
```typescript
// es67_snippet.js

// declare
class Foo {
  bar0;
  bar1 = "hello";  
  static sBar0;
  static sBar1 = "HELLO";
} 

// test
let foo = new Foo()
foo.bar0 = "world"
Foo.sBar0 = "WORLD"

// expect `hello world HELLO WORLD`
console.log(foo.bar1, foo.bar0, Foo.sBar1, Foo.sBar0)
```
This would compile down to: 
####  ES5 Equivalent
```typescript
// es5_equivalent.js

// declare
var Foo = (function () {
    function Foo() {
        this.bar1 = "hello";
    }
    return Foo;
}());
Foo.sBar1 = "HELLO";

// test
var foo = new Foo();
foo.bar0 = "world";
Foo.sBar0 = "WORLD";

// expect `hello world HELLO WORLD`
console.log(foo.bar1, foo.bar0, Foo.sBar1, Foo.sBar0);
```
(from [typescript playground](https://www.typescriptlang.org/play/#src=%2F%2F%20declare%0D%0Aclass%20Foo%20%7B%0D%0A%20%20bar0%3B%0D%0A%20%20bar1%20%3D%20%22hello%22%3B%20%20%0D%0A%20%20static%20sBar0%3B%0D%0A%20%20static%20sBar1%20%3D%20%22HELLO%22%3B%0D%0A%7D%20%0D%0A%0D%0A%2F%2F%20test%0D%0Alet%20foo%20%3D%20new%20Foo()%0D%0Afoo.bar0%20%3D%20%22world%22%0D%0AFoo.sBar0%20%3D%20%22WORLD%22%0D%0A%0D%0A%2F%2F%20expect%20%60hello%20world%20HELLO%20WORLD%60%0D%0Aconsole.log(foo.bar1%2C%20foo.bar0%2C%20Foo.sBar1%2C%20Foo.sBar0)); and [babel](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Ces2016%2Ces2017%2Cstage-2%2Cstage-3&targets=&browsers=&builtIns=false&debug=false&code=%2F%2F%20declare%0D%0Aclass%20Foo%20%7B%0D%0A%20%20bar0%3B%0D%0A%20%20bar1%20%3D%20%22hello%22%3B%20%20%0D%0A%20%20static%20sBar0%3B%0D%0A%20%20static%20sBar1%20%3D%20%22HELLO%22%3B%0D%0A%7D%20%0D%0A%0D%0A%2F%2F%20test%0D%0Alet%20foo%20%3D%20new%20Foo()%0D%0Afoo.bar0%20%3D%20%22world%22%0D%0AFoo.sBar0%20%3D%20%22WORLD%22%0D%0A%0D%0A%2F%2F%20expect%20%60hello%20world%20HELLO%20WORLD%60%0D%0Aconsole.log(foo.bar1%2C%20foo.bar0%2C%20Foo.sBar1%2C%20Foo.sBar0)) is almost identical) 

## Potential Bug 
Not sure if this is already known, but if you run the `ES6/7 Snippet` through lebab like:
```
lebab es67_snippet.js --transform <transform>
```

It fails with error:
```
%APPDATA%\npm\node_modules\lebab\node_modules\espree\espree.js:441
        throw err;
        ^

SyntaxError: Unexpected token ;
    at Parser.instance.raise.instance.raiseRecoverable (%APPDATA%\npm\node_modules\lebab\node_modules\espree\espree.js:437:19)
    at Parser.instance.unexpected (%APPDATA%\npm\node_modules\lebab\node_modules\espree\espree.js:470:14)
    at Parser.pp.expect (%APPDATA%\npm\node_modules\lebab\node_modules\acorn\dist\acorn.js:629:26)
    at Parser.pp$3.parseMethod (%APPDATA%\npm\node_modules\lebab\node_modules\acorn\dist\acorn.js:2356:8)
    at Parser.pp$1.parseClassMethod (%APPDATA%\npm\node_modules\lebab\node_modules\acorn\dist\acorn.js:1253:23)
    at Parser.pp$1.parseClass (%APPDATA%\npm\node_modules\lebab\node_modules\acorn\dist\acorn.js:1233:12)
    at Parser.pp$1.parseStatement (%APPDATA%\npm\node_modules\lebab\node_modules\acorn\dist\acorn.js:755:17)
    at Parser.pp$1.parseTopLevel (%APPDATA%\npm\node_modules\lebab\node_modules\acorn\dist\acorn.js:684:23)
    at Parser.parseTopLevel (%APPDATA%\npm\node_modules\lebab\node_modules\espree\espree.js:294:34)
    at Parser.parse (%APPDATA%\npm\node_modules\lebab\node_modules\acorn\dist\acorn.js:541:15)
PS C:\Users\makombo\Documents\Projects\Rubbish\lebabtry>
```
## Feature Request
As an added bonus, it would just be amazing lebab could transform the ` es5_equivalent.js` as shown above, into `es67_snippet.js` ... This is currently not the case.

Thanks for all the hard work!!!

**Comment by nene** [comment]
ECMAScript class properties are not part of ES6 or ES7. They're still in stage 1 draft status: https://tc39.github.io/proposal-class-public-fields/

Lebab uses [Espree parser](https://github.com/eslint/espree) which doesn't yet support this syntax. Lebab won't support this until we switch the parser or Espree starts supporting this syntax.

**Comment by somombo** [comment]
@nene Actually from https://github.com/tc39/proposals, that proposal is actually in Stage 2. Looks like they havn't updated the page you provided yet.

It is unfortunate that you can't support this, since this syntax is supported just fine in babel. 

Naively, I might suggest that one way to go about it, might be to run the code through babel to generage something that looks like my `es5_equivalent.js` and then run that through an augmented lebab to produce something that looks like `es67_snippet.js`

Thanks for your response anyhow.
