### ISSUE TITLE
template transform doesn't transform nested concatenation

### ISSUE THREAD

**Issue by josephfrazier** [lebab/lebab#242]
EDIT: It looks like this has something to do with a BinaryExpression not being traversed. The test case can be reduced to:

Input:

```js
'' + () => 'a' + 2
```

Output:

```js
`${() => 'a' + 2}`
```

Expected output:

```js
`${() => `a${2}`}`
```

Note that removing the empty string from the input causes the function expression to be transformed correctly:

```js
() => 'a' + 2
```

becomes:

```
() => `a${2}`
```

---

Demo: https://runkit.com/josephfrazier/runkit-npm-lebab-template-nested/1.0.0

Input:

```js
let intro;
const data = {};
const subName = ''
const subParts = /foo/g;
let capName;
intro + data[subName].pattern.replace(subParts, (match, paren, backref) => {
            return '(?<' + capName + '>';
}) + ')';
```

Output:

```js
let intro;
const data = {};
const subName = ''
const subParts = /foo/g;
let capName;
`${intro + data[subName].pattern.replace(subParts, (match, paren, backref) => {
            return '(?<' + capName + '>';
})})`;
```

Expected output:

```js
let intro;
const data = {};
const subName = ''
const subParts = /foo/g;
let capName;
`${intro + data[subName].pattern.replace(subParts, (match, paren, backref) => {
            return `(?<${capName}>`;
})})`;
```

Note the second-to-last line.

**Comment by josephfrazier** [comment]
I realized that this could be due to the inability to infer the type of `capName`, as needed by https://github.com/lebab/lebab/blob/b384996100e166a68b4065d82995474f7aff8972/src/transform/template.js#L15. This doesn't seem to be the case, though, as the following code *does* get transformed to use a template literal:

```js
let capName;
function f() {
  return '' + capName;
}
```

**Comment by nene** [comment]
I've merged in the fix. We'll see how soon I can get a release out as well. I also want to get the #233 PR in.

**Comment by josephfrazier** [comment]
Thanks for the merges. I'm looking forward to the release!

**Comment by nene** [comment]
Sorry for the enormous delay, release 2.7.3 is now finally out with this fix included. Thanks once more.
