### ISSUE TITLE
Convert let to const where appropriate

### ISSUE THREAD

**Issue by kofifus** [lebab/lebab#245]
This would be very useful

ATM in order to get 'maximum constness' I replace all let with var and then run the let transform, this is ugly and possibly not safe.

Thx!

**Comment by nene** [comment]
This functionality is already available in ESLint using `--fix` option with [prefer-const](http://eslint.org/docs/rules/prefer-const) rule.

I don't think it's worth reimplementing it in Lebab. It's also not really related to switching from ES5 to ES6.

**Comment by kofifus** [comment]
The point is, I (and I assume others) use lebab not only to convert old project but to make sure new code is making best use of the new ES6 features .. for example using the for-of, spread and default transformations. In this scenario it would be very useful to change let to const. Can this be added ?

(ESLint is a totally different thing, I for example use visual studio 2017 and so have no need for it)

Thx!

**Comment by nene** [comment]
Perhaps you are right. But I first need to wait for others to request this functionality as well, before deciding whether it's really the way how Lebab is used.
