### ISSUE TITLE
Expose sourcemaps through api

### ISSUE THREAD

**Issue by kshutkin** [lebab/lebab#246]
Hi,

I tried to integrate this tool in build process to convert commonjs modules to es6 and it works surprisingly well. I like the idea to remove old commonjs wrappers and to get better tree-shaking.

But to really use it in production I need sourcemaps. I think recast provides sourcemaps so why not to expose them?

**Comment by nene** [comment]
You should not use Lebab in production. It's meant to be a tool you use once for converting your source from ES5 to ES6 and then continuing in ES6.

It's simply not safe enough tool to use in production. If you want to do that, I can't stop you, but I'm not going to add any functionality to facilitate the use in production.
