### ISSUE TITLE
Get the lebab library

### ISSUE THREAD

**Issue by JenneyJ** [lebab/lebab#248]
HI,

I use lebab for testing purpose in JSfiddle, there I put the reference 
https://rawgit.com/hugeen/lebab-experiment/master/lebab.js

but it doesn' t parse the code as expected, for example arrow function are not working but if I test the same file in the playground you have provided it working as expected ...
1. Does this library is up to date ? 
2. if I want to download the minified up-to-data version from this repo,is it possible ?if yes which file should I use

Thanks!

**Comment by nene** [comment]
Hi Jenney,

I can't really tell what you mean by "array functions are not working" unless you provide some example.

1. The [playground](http://lebab.io/try-it) is definitely outdated. I'm not under control of this site, so I can't update it. Usually people complain that it's the playground that doesn't work. Otherwise the library itself should be up to date.
2. There is no minified version of the library available. You can build one by yourself from npm using Browserify or Webpack.

**Comment by JenneyJ** [comment]
HI Nene,

I did what you suggest with broswerify and uglify since I want to use the latest version (2.7.3) and not the version that I provided in the url since it can be old...(not sure how to check it )

As your suggestion I've installed browserfiy and uglify and create a file main.js with the following content 
var lebab = require("lebab");

boundle it with the following command  

browserify main.js | uglifyjs > bundle.js


Now when I call to the code like following:

const {code, warnings} = lebab.transform('var f = function(){};', ['let', 'arrow']);

I got error 
bundle.js:1 Uncaught TypeError: _lodash2.default.assign is not a function
    at Object.480.estraverse (bundle.js:1)
    at s (bundle.js:1)
    at bundle.js:1


what am I doing wrong ?

Thanks!

**Comment by uniibu** [comment]
If you simply want to do a test programmatically, you can always play with https://runkit.com/npm/lebab

If you want to test locally, install nodejs locally and do it from there. 

If you want test it in browser, as suggested you can use browserify. You just need to expose the module globally/window. So either declare it like:

```js
global.lebab =require ('lebab') 
// or directly via window
window.lebab = require ('lebab')
```

**Comment by JenneyJ** [comment]
Thanks, but how should I use it with require.js ?
I've tried the following and it doesn't work

what I did is npm init &

npm install lebab --save
create file main.js and put the following code

var lebab = require("lebab");
And run the command

browserify --standalone someName main.js | uglifyjs > bundle.js
it finish sucessfully

Take the bundle.js file put it under converter/service folder

And try to require it like following:

define(["converter/service/bundle"], function (bundle) {

We are using require.js mechanism and it doest work, any idea? 

Thank you!

**Comment by JenneyJ** [comment]
please see this reference
http://www.forbeslindesay.co.uk/post/46324645400/standalone-browserify-builds

I cannot use the window suggestion just AMD ... :(

**Comment by uniibu** [comment]
Hi, i created a PR https://github.com/lebab/lebab/pull/250 for a Production build which you can use on your project by simple requiring either lebab.js or lebab.min.js from the `dist` folder. It is a umd build, so you can also use it on your browsers by simply fetching it using the `<script>` tag

**Comment by uniibu** [comment]
Just in case people passes by on this issue. You can get the latest Browerified version of Lebab by going to
https://wzrd.in/standalone/lebab@latest or if you want to use `cdn.rawgit` you can also get the latest here https://umdfied.herokuapp.com/umdfied/lebab/latest

**Comment by nene** [comment]
The Browserify build is now linked from README.
