### ISSUE TITLE
Lebab Live editor

### ISSUE THREAD

**Issue by uniibu** [lebab/lebab#253]
Seems like https://lebab.io/try-it is not updated and @nene do not have access to this, so in case people want to try out the latest Lebab version without installing it on their machines, I created this

[Lebab - Community Editor](https://uniibu.github.io/lebab-ce/ ) - You can view the source here  [Source](https://github.com/uniibu/lebab-ce)

It uses the latest version of Lebab, If Lebab updates, this also automatically fetches and updates. So it will always be up to date.

Main Features:
- Customizable Options. You can choose which Lebab options you like to test.
- Optional Minify and Transpile using Babel and Babili.

Fork,Clone,Download:
- You can simply fork the repo and use it directly using Github pages.
- You can also Clone it to your own server and run it just like a regular website.
- You may download the repo locally, but it must be ran on a local webserver such as `wamp` for windows and the likes.

Tested on:
FF - 54.0.1 
Chrome - 59.0

Note** Since the code uses `webworkers`, it must be ran on a web server since modern browsers will not allow you to run a web worker locally.

**Comment by nene** [comment]
Hey, this is totally awesome! Many thanks for the effort.

I've linked it from the README page of the repo (replacing the old live demo link).

**Comment by nene** [comment]
A few additional thoughts...

**I ponder over the usefulness of the Minify and Transpile options.**

Transpile is somewhat fun for me to play with. In theory running code through Lebab and Babel should result in the same code. But of course in practice there will be differences which are interesting to see. It can also serve as a bit of a confirmation that Lebab indeed outputs enough of a well-formed code that Babel can understand it. Though in reality Lebab more likely crashes than produces a code with syntax error - the subtle changes in behavior that Lebab might introduce will not be caught this way.

But what disturbs me more is that both Minify and Transpile suggest one would use Lebab in some build chain to generate compiled code for machines. While I see Lebab as an opposite of that - a tool to make your old ES5 code more pleasant ES6 code to be read by humans.

**The default code sample could be improved upon.**

It's using mostly the same code that the old try-it site uses, which I think is a bit too long, concentrates too much on some of the more subtle features, and does not demo some of the big features at all.

I pieced together a small snippet that should show off the most of the main features in more compact and compelling way:

```js
'use strict';
var _ = require('lodash');

function Person(cfg) {
  this.names = [cfg.fname, cfg.lname];
}
Person.prototype.greet = function(title) {
  title = title || "Mr";
  var fullName = this.names
    .map(function(n) {
      return _.upperFirst(n);
    })
    .join(" ");

  return "Hello " + title + " " + fullName + "!";
};
Person.prototype.greetWithAllTitles = function() {
  for (var i = 0; i < arguments.length; i++) {
    var title = arguments[i];
    this.greet(title);
  }
};

module.exports = Person;
```

**Finally... may I suggest eating your own dogfood :)**

That is, it would be nice to have the source code of lebab-ce fully written in ES6, which should a simple matter of running it through Lebab :)

**Comment by uniibu** [comment]
Well ive been using Lebab via (self-made sublime) plugin for all my projects. I have it on auto-format on each save, and will outline the line if there is a syntax error. And I can pretty much say, it has worked 90% of the time. Tho i must admit, I'm not using the full options. 

And recently(till now), I'm working on a private project which basically is a 'central api manager' in which admins and the likes, can generate api endpoints, explore existing endpoints, creating new api with an option to add a code snippet, etc. And I find Lebab to be very useful in this case. For one, it enforces strict rules on how the code should look like across the entire project even if it was written by multiple persons. 

In regards to transpiling/minify, i just find it cool to add. :) On the other side, you might also be thinking that way because you mostly look at Lebab to be a `server-side-developer-tool`. Tho in my opinion, Lebab is something that gives people a sneak peek of what coding looks-like in the future, weather you're a developer or not. But like i said, that's the future, we are still a bit far from having a full es6 complaint browsers, specially user's that don't update their browsers, that's where the transpile/minify(Babel) comes in. So i think i find it useful and fun at the same time. 

I've read some post of yours that you primarily think Lebab as a tool and is not safe to be used for production,which i disagree. Any tool,framework,platform,module is not safe to be used for production unless you know what you are doing. Tho Lebab is still not perfect, it is as ready as the other tools out there, as long as one knows what he is doing.

**Comment by nene** [comment]
That's pretty interesting. So it's like you're writing `{foo: foo}` and Lebab transforms it to `{foo}` when you save?

I'd agree that it's a fairly safe use of Lebab. Especially because you're doing it at development time - so that when Lebab does something wrong, you'll notice it immediately.

What I want to steer people away from, is using Lebab blindly, without looking at the code that it generates - like one would use Babel, or really any ordinary compiler. I guess that mostly aligns with your thought of knowing what you're doing.

**Comment by Haroenv** [comment]
I thought it wasn’t working first, but then I started looking around in the devtools and the actual code blocks showed up, that was about 3 seconds after page load. Just something to notice. This is on a 2015 13” MBP, on good (70MBps) connection. On repeat load it took just under a second.

**Comment by uniibu** [comment]
Hi, thanks for checking it out. Once you load the editor, it checks out for any new version of lebab, it then takes the latest version. Since lebab does not have its own browser version, it gets the browserified version of it using a third party service. It is why its taking some time on the first load, but once it loads, it will then be cached on your browser, so next reaload will be faster.

**Comment by nene** [comment]
@uniibu while investigating #259 I discovered that the Community Editor runs the code twice through lebab (which in the case of that issue meant Lebab first generated invalid JS and then failed to parse that, ending up crashing - took me a while to figure out why the editor crashes while the command line Lebab finishes without crashing).

I wonder why have these two passes?

**Comment by uniibu** [comment]
Hi, i will check it out soon as i get on my pc.

On Sep 15, 2017 3:43 PM, "Rene Saarsoo" <notifications@github.com> wrote:

@uniibu <https://github.com/uniibu> while investigating #259
<https://github.com/lebab/lebab/issues/259> I discovered that the Community
Editor runs the code twice through lebab (which in the case of that issue
meant Lebab first generated invalid JS and then failed to parse that,
ending up crashing - took me a while to figure out why the editor crashes
while the command line Lebab finishes without crashing).

I wonder why have these two passes?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/lebab/lebab/issues/253#issuecomment-329707310>, or mute
the thread

**Comment by uniibu** [comment]
@nene I've removed the double transform on Community Editor. https://github.com/uniibu/lebab-ce/commit/e0ed10dcd5ba8ae9c439c33d587865bcdf170384 
This was initially to 'fix' self invoked anonymous functions from adding extra parentesis.
`(function (){
  console.log('hi')
})()`
will result to
`((() => {
  console.log('hi')
}))()`
Thus running transform twice removes that extra parentesis. But since it crashes on some occassions i have removed it already to prevent more issues and confusion rather than solution.

Cheers!

**Comment by nene** [comment]
Great!

I'm closing down this task. We can open up additional issues in https://github.com/uniibu/lebab-ce repo when the need arises.
