### ISSUE TITLE
Supported feature in lebab

### ISSUE THREAD

**Issue by JenneyJ** [lebab/lebab#256]
Hi,

1. Does lebab support only ES6 or already ES7-8 ..., if yes, is there a way to restrict it just to es6 etc? 

2. I tried to check the functionality with various content and for example file which contain @ &$ etc 
in this case I got errors, SyntaxError: Unexpected character '@'
My question is since I use the api like following:

var resp= bab.transform('var f = function(){};', ['let', 'arrow']);
var code = resp.code;
var warnings = resp.warnings;

How it's recommended to avoid or catch those errors?

**Comment by uniibu** [comment]
Use try catch
```js
try {
  const {code,warnings}= lebab.transform('var f = function(){%^$};', ['let', 'arrow']);
  console.log(code, warnings)
} catch(err) {
	//do what you want with the err
}
```

**Comment by nene** [comment]
Lebab uses Espree parser, so it's dependent on [what Espree supports.](https://github.com/eslint/espree#what-ecmascript-6-features-do-you-support) Notably Espree optionally supports some experimental features like JSX, and object spread which Lebab also enables.

Espree actually allows configuring itself to just support one ECMAScript version. But one can't configure it through Lebab. If you would describe your use case for that, we could consider adding a support for such configuration.
