### ISSUE TITLE
Newline is not converting in from es5 to es6

### ISSUE THREAD

**Issue by Tamerlan1993** [lebab/lebab#264]
I write code like this

```
var name="Lebab"
console.log('Hello'+name+'how \n are you ?');
```
but it convert like this
```
const name="Lebab";
console.log(`Hello${name}how \n are you ?`);
```

**Comment by nene** [comment]
I guess you would expect to get:

```
console.log(`Hello${name}how 
 are you ?`);
```
However, now you end up with significant whitespace at the end of the line (which used to surround `\n`). It doesn't seem like a good outcome either.

Also, when that console.log is indented, the actual newline will mess up your indentation.

I have considered transforming the newlines before, but it seems to create more problems than it solves.
