### ISSUE TITLE
Simple function returning class object to es6 class?

### ISSUE THREAD

**Issue by goldingdamien** [lebab/lebab#265]
I am looking for a way to convert old code with classes in the format below into es6 classes. Is this something possible now or in the future with this library?

```
function MyClass(){
  var myClassInstance = {};
  myClassInstance.property = 'string';
  myClassInstance.myFunction = function(){
    //
  }

  return myClassInstance;
}

var newClassInstance = MyClass();
```

**Comment by nene** [comment]
A problem with this code is that it's just a function that returns some object. It doesn't make use of prototypes. You don't even call `new MyClass()` to create an instance, you just call `MyClass()`.

But if this were an ES6 class, you would need to start calling `new MyClass()`. Transforming all these instantiations will be much trickier to accomplish as Lebab would need to trace through all files to catch all cases where `MyClass()` is called. Currently Lebab does not look beyond a single file.

Additional problems will arise when inside this MyClass constructor you reference the constructor parameters from the methods:

```js
function MyClass(name) {
    var obj = {};
    obj.getName = function() { return name; };
    return obj;
}
```

Lebab would then need to make up a field for this parameter (ensuring it wouldn't overlap with any of the existing fields).

So as you see, this thing is getting pretty complicated...

You'd always welcome to submit a pull request if you're interested in implementing support for such a thing. But adding support for this is not in the pipeline of Lebab.

**Comment by goldingdamien** [comment]
Thank you for your detailed response.
Yes, I looked at it myself but realized it would be quite time consuming to do.
What old formats of classes would be possible to convert to es6 classes?

**Comment by uniibu** [comment]
@goldingdamien 

Old prototype format
```js
function Person(name) {
  this.name = name;
}
Person.prototype.greet = function(title) {
  title = title || "Mr";
  console.log("Hello " + title + " " + this.name);
};
var person = new Person("goldingdamien");
person.greet();
// Hello Mr goldingdamien
```

Will transform to:
```js
class Person {
  constructor(name) {
    this.name = name;
  }
  greet(title = "Mr") {
    console.log(`Hello ${title} ${this.name}`);
  }
}
const person = new Person("goldingdamien");
person.greet();
// Hello Mr goldingdamien
```

**Comment by goldingdamien** [comment]
Thank you. I will remember that for later.
