### ISSUE TITLE
support for Object.defineProperties()

### ISSUE THREAD

**Issue by FishOrBear** [lebab/lebab#267]
```js

function Matrix()
{

}

Object.assign(Matrix.prototype,
    {
        isMatrix: true,

        setMatrixValue: function (x)
        {
            //...
            return this;
        }

        //...
    }
)


Object.defineProperties(Matrix.prototype,
    {
        center: {
            get: function ()
            {
                return undefined;
            },

            set: function (value)
            {
                //...
            }
        },

        length: {
            value: 12,
            writable: true
        },

        size: {
            value: 1,
            writable: false
        },

        postion: {}
    }
)
```

output:  

```js
class MatrixEs6
{
    //Object.assign
    isMatrix = true;

    setMatrixValue(x)
    {
        //...
        return this;
    }

    //Object.defineProperties

    get center()
    {
        return undefined;
    }
    set center(value)
    {
        //..
    }
    length = 12;
    readonly size = 1;

    postion;
}

```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperties

**Comment by nene** [comment]
@FishOrBear please describe what would you expect Lebab to output for this code.

**Comment by FishOrBear** [comment]
@nene  Hi, I updated Example

**Comment by nene** [comment]
1. Currently Lebab only supports the singular `Object.defineProperty()` when it's used for getters/setters. I't shouldn't be hard to extend it to support the plural version as well for the get/set case.

2. Lebab doesn't have support for [class fields](https://github.com/tc39/proposal-class-fields), which aren't officially part of ECMAScript yet. So far Lebab hasn't supported any non-final features of ECMAScript. And therefore Lebab doesn't handle uses of `Object.defineProperty` for normal fields. 

3. I wasn't aware of this syntax for readonly properties:
```
readonly size = 1;
```
Perhaps you can enlighten me by referencing a spec/proposal that describes this.

4. You're also asking for support for recognizing `Object.assign()`.

As you see, you're asking for 4 features. The first one I could consider implementing... but I'm not very motivated as you're the first one who has asked for that.

The class fields support is probably something that more people would be interested in, even though it's not official ECMAScript yet. So I'd be willing to help with that.

A pull request would be the most welcome approach if you're really interested in these features..

**Comment by nene** [comment]
Closing because of lack of additional feedback from author.
