### ISSUE TITLE
String to template literal feature?

### ISSUE THREAD

**Issue by James-A1** [lebab/lebab#270]
Hi guys, just wanted to say that I am impressed with lebab so far.

**What**
I am trying to create a converter with babel and lebab. The idea is to pop in some es6 syntax, convert it into es5 with babel. Then when the time comes, convert the es5 syntax into es6 with lebab. I'm not looking for perfect conversion, however there is just one difficulty I noticed when converting template literals to strings and back.

Here is a sample:
```
//Input into babel:
var someHTML = `
  <div> 
    <h1>Hello World</h1>
  </div>
`;

//output from babel:
var someHTML = "\n  <div> \n    <h1>Hello World</h1>\n  </div>\n";
```

But, when converting the output from above with lebab, it doesn't convert the string back to something like the original string literal:
```
//input to lebab
var someHTML = "\n  <div> \n    <h1>Hello World</h1>\n  </div>\n";

//output
const someHTML = "\n  <div> \n    <h1>Hello World</h1>\n  </div>\n";

//sort of expected the original:
var someHTML = `
  <div> 
    <h1>Hello World</h1>
  </div>
`;
```

This is the expected behavior of course. After all, it's only vaguely implied that when converting back with the `\n` in the string that it is to be a template literal. At the moment I don't see anyway to convert the strings back to template literals. Still, it would be useful.

Thank you.

**Comment by nene** [comment]
There is a somewhat related issue #88, which I created a long time ago. I guess it won't be ever solved, as you can't really guess the intentions of the author.

Sometimes you just happen to have a long multilinear string, at other times you want to explicitly state the presence of newline character. Additionally - converting \n to actual newline can ruin your indentation, which might or might not be acceptable for you.

Won't fix.
