### ISSUE TITLE
Minor Bump?

### ISSUE THREAD

**Issue by uniibu** [lebab/lebab#274]
With the merging of https://github.com/lebab/lebab/pull/268 and https://github.com/lebab/lebab/pull/269 I think its a good time to do a minor bump release of Lebab? @nene @mohebifar

**Comment by nene** [comment]
Hey @uniibu, it's been a while... but now finally done.

However, this really warranted a major version bump, as splitting of the arrow transform breaks existing behavior. Hopefully fairly mildly, but still.

So now 3.0.0 is out.
