### ISSUE TITLE
semicolons

### ISSUE THREAD

**Issue by jimmywarting** [lebab/lebab#276]
This isn't a major issue, but I'm using Standard.js (no semicolon) and i can always fix the style afterwards with `npx standard --fix` but It always bugs me that when I enter this:

```js
const foo = 'bar'
var name = 'Bob'
```
i get out 

```js
const foo = 'bar'
const name = 'Bob';
```

Can you maybe preserve the code style a little bit more and only convert the actual code that needs to be updated? meaning: leave the `;` out of it (treat it as a comment or something)
for example this:

```js
var foo = 'bar';
var name = 'Bob'

// would transform into this:

const foo = 'bar';
const name = 'Bob'
```

**Comment by nene** [comment]
This is really an issue for Recast library which Lebab uses to do the transforms.

You can report it there, though I guess it's a known issue.

Won't be fixed in Lebab itself. Sorry.
