### ISSUE TITLE
IIFE Arrow function unexpected token

### ISSUE THREAD

**Issue by streichman** [lebab/lebab#283]
When transforming IIFE to use arrow functions, there should be a check to make sure the calling parenthesis are outside the enclosure parethesis:

unexpected token:
```js
(() => {
   //...
}());
```

correct: 
```js
(() => {
  //...
})();
```

https://stackoverflow.com/questions/22138550/immediate-function-using-javascript-es6-arrow-functions

**Comment by nene** [comment]
Hi @streichman 

Could you please provide the input code which results in this invalid output.

**Comment by streichman** [comment]
```js
(function() {
....
}());
```

**Comment by nene** [comment]
Perhaps you're not using the latest version of Lebab, as for me this code produces exactly the correct output that you are expecting to get:

```js
(() => {
  //...
})();
```

You can try the latest version in here: https://lebab.unibtc.me/editor

**Comment by streichman** [comment]
You are correct, my apologies - looks like it is a problem with ESLint showing an error when it should not.
