### ISSUE TITLE
How to convert Promise based code to Async await based code?

### ISSUE THREAD

**Issue by adroit1234** [lebab/lebab#284]
My testcase code looks like this- 

```js
it("should do something", function(done) {
       function1("someparam").then(() => {
            function2("someparam").then(() => {
                functionN("someparam").then(() => {
                   comp(expectedfile,0.001,actualfile, done);
                });
             });
       });
```
I want to use async await to make this more readable and avoid all this nesting. Can someone help me understand how to do it?

Regards
+Ad

**Comment by nene** [comment]
Hi @adroit1234, I'm not really sure what you're asking for.

Do you need help in understanding how you can convert promises-based code to async/await? Lebab doesn't help you here. Perhaps ask from StackOverfow?

Or do you want to propose a way in how Lebab could solve this problem automatically.
There already exists a feature request for Promise -> Async/Await #202
