### ISSUE TITLE
Lebab.io not working anymore

### ISSUE THREAD

**Issue by arguiot** [lebab/lebab#286]
The website `lebab.io` is not working anymore. Consider to buy the domain or just use gh-pages

**Comment by RobertJGabriel** [comment]
:'(

**Comment by nene** [comment]
Maybe it's for the better. It was outdated anyway.

The original author of Lebab, @mohebifar, created it, but he has move on elsewhere and hasn't kept the site up to date.

Then @uniibu came along created an alternative: https://lebab.unibtc.me/

**Comment by nene** [comment]
I've removed the one remaining link to lebab.io from README.
