### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by rwaldron** [lebab/lebab#292]
Clicking the link in the readme, or visiting https://lebab.unibtc.me/editor directly results in: 

![image](https://user-images.githubusercontent.com/27985/57085274-dcca9100-6cc9-11e9-9b46-3349f8d96270.png)

**Comment by nene** [comment]
@uniibu

**Comment by uniibu** [comment]
@nene There was an issue with the DNS.. This should be fixed now for some users. while some would need to wait for the DNS to properly propagate.

![image](https://i.gyazo.com/a247639dede8ea5da0b313bc572efa5e.png)

**Comment by nene** [comment]
Seems to work now.

Thanks for all your efforts!

**Comment by rwaldron** [comment]
Thanks!!
