### ISSUE TITLE
Support transforming Resig's Simple JavaScript Inheritance Classes to ES6 Classes

### ISSUE THREAD

**Issue by ciarancourtney** [lebab/lebab#293]
I'd like to migrate a large app that extends [Resig's Simple JavaScript Inheritance](https://johnresig.com/blog/simple-javascript-inheritance/) `Class.js`

From:

````js
/*global NS, jQuery, window, document */

NS.Shell = NS.Class.extend({

    init: function (container) {
        var self = this;

        self.container = container;

        self.respond_to_window_size();
    }, 
    
    respond_to_window_size: function () {
        var self = this;

        NS.Registry.get('ResponsiveDesign').respond(jQuery(window), self.container.parent());
    }
})
````

To:

````js
export class Shell {

    constructor(public container) {
        const self = this;

        self.container = container;

        self.respond_to_window_size();
    }

    respond_to_window_size() {
        const self = this;

        const rd = new ResponsiveDesign()
        rd.respond(jQuery(window), self.container.parent());
    }
}
````

`NS` is just a **N**ame**S**pace object on which everything hangs.

An example of an extended class would be:

From:

````js
/*global NS, jQuery, window, document */

NS.LoginPage = NS.Shell.extend({
    init: function (container) {
        var self = this;
        self.call_super(container);
        self.container = container;
    }
})
````

To:

````js
export class LoginPage extends Shell {
    constructor(public container) {
        const self = this;
        super(container);
        self.container = container;
    }
}
````

I have no idea where to start adding this to lebab, any help would be greatly appreciated.

**Comment by nene** [comment]
You would need to look inside the `class` transform: https://github.com/lebab/lebab/tree/master/src/transform/class

The bad news is that it's the most complex transform that Lebab performs. I'm not really sure how similar/different the transforming of Resig's Class system would be to what Lebab already does. For one, we've had a request open for years to support transforming namespaces.

It might be that you're better off using escodeshift that's probably a more approachable tool than Lebab. So you could perhaps more easily build a one-off tool to perform the transform in your specific use case in a single code-base.

**Comment by ciarancourtney** [comment]
Thanks @nene I ended up using a few regex incantations after trying a few AST tools
