### ISSUE TITLE
lebab.io infected with malware.

### ISSUE THREAD

**Issue by mpalpha** [lebab/lebab#294]
doh malware on lebab.io

**Comment by uniibu** [comment]
> doh malware on lebab.io

Did you mean the website `lebab.io`? The lebab.io domain name is no longer connected with this repo/project. 

However, you can always test and use the Community Edition of the lebab which is located at https://lebab.unibtc.me

**Comment by nene** [comment]
Huh, that's bad indeed. @mohebifar, maybe you can do something about that. The rest of us cannot help with that.

**Comment by mohebifar** [comment]
That's really bad. Unfortunately, I don't have access to this domain anymore. I'm sorry about that. I don't know what I can do now. I just see we're not linking to it anywhere anymore.

**Comment by nene** [comment]
Ah... I see that lebab.io no more contains anything about lebab.js. So I guess it's ok then.
