### ISSUE TITLE
Request for Lebab site to be offline with PWA.

### ISSUE THREAD

**Issue by illvart** [lebab/lebab#297]
Hi, I really love **Lebab** and always use this site. But when I was offline I was unable to use Lebab. Please become a **PWA**. Thank you!

**Comment by nene** [comment]
I suppose PWA stands for Progressive Web Application.

This repository is for the Lebab library / command line tool, which works perfectly when you're offline :)

You probably want to direct your feature request towards https://github.com/uniibu/lebab-ce
I admit that this repo is far from easy to locate if you're not aware of it already :)

Better yet would be to create a pull request, I don't think @uniibu would oppose to such a feature.
