### ISSUE TITLE
async/await function convert

### ISSUE THREAD

**Issue by GoddessLuBoYan** [lebab/lebab#300]
I have an async function. (my code)
`async play()
{
    await 111;
    await 222;
    await 333;
}`

and it compiles like this (compiler code)

`play = function () {
return __awaiter(this, void 0, void 0, function () {
    return __generator(this, function (_a) {
        switch (_a.label) {
            case 0: return [4 /*yield*/, 111];
            case 1:
                _a.sent();
                return [4 /*yield*/, 222];
            case 2:
                _a.sent();
                return [4 /*yield*/, 333];
            case 3:
                _a.sent();
                return [2 /*return*/];
        }
    });
});`

I want to convert the compiler code to my code, but I try all options in lebab, nothing works.
So, I want to know if there is some similar code like this and can convert to the async-type.
If not, I want to try to edit the lebab to solve this problem, but I don't know where to read start, which functions/variables can I use, and where should I edit. Please give me some ideas.

Thank you very much.

**Comment by nene** [comment]
Perhaps you took it literally that Lebab "does the opposite of what Babel does".

The goal of Lebab is to convert human-written ES5 code to similar ES6 code. It won't convert Babel-generated ES5 code back to the original ES6 code.

Additionally, Lebab doesn't support conversion of async-await yet.

So you're really out of luck here.

**Comment by GoddessLuBoYan** [comment]
oh,what a pity!
