### ISSUE TITLE
class transform does not see “require('util').inherits(C, A);”

### ISSUE THREAD

**Issue by dilyanpalauzov** [lebab/lebab#321]
This input
```javascript
function A() {}

A.prototype.b = function() {}

function C () {
    A.call(this);
}

require('util').inherits(C, A);
```
produces
```javascript
5:  warning  Function C looks like class, but has no prototype  (class)
class A {
    b() {}
}

function C () {
    A.call(this);
}

require('util').inherits(C, A);
```

It does not see `util.inherits()`

**Comment by nene** [comment]
Thanks for reporting. But for now, won't fix this as it's more of an odd corner case and Lebab behaves correctly: it doesn't do the transform because it encounters unfamiliar syntax. It even prints a nice warning.
