### ISSUE TITLE
demo page

### ISSUE THREAD

**Issue by danielhaim1** [lebab/lebab#334]
fyi, the demo page seems to be down due to dns/domain issues 🥠

**Comment by badbabykosh** [comment]
Anyone else have a live demo page up and running?

**Comment by live627** [comment]
I''e got a clone at https://live627.github.io/lebab.io/try-it but requests to the cdn are denied

![Untitled](https://user-images.githubusercontent.com/431799/179146912-5e11c356-3963-434c-b97a-51c5ac9e7194.png)

**Comment by m5nv** [comment]
This [commit](https://github.com/lebab/lebab/commit/c5489ca52bd1cfcfcde42d6c5378787780212276) introduced the change. It looks like the domain `lebab.io` has been lost to squatters (?)

**Comment by jonluca** [comment]
I deployed a different version here https://lebabjs.com/ that should be working, if anyone is just looking for a working simple UI

**Comment by nene** [comment]
Thanks @jonluca!

Changed the link in README to point at lebabjs.com.

Don't know what has happened with the old link. It used to be just a GitHub page, but looks like it was redirected elsewhere at one point, and that domain no more works.

**Comment by danielhaim1** [comment]
thanks @nene!

**Comment by nene** [comment]
I have now replaced the Lebab demo linked from this repo with http://lebab.github.io/

Over the years I have relied on various third parties to provide a demo page, but for some reason or another these pages have gone down. To avoid such problems in the future and give me more control over the demo page, I've now finally built my own.

**Comment by live627** [comment]
Thanks, this new demo is great.

**Comment by danielhaim1** [comment]
Thanks again @nene really useful demo.
