### ISSUE TITLE
Transform prototype methods as arrow

### ISSUE THREAD

**Issue by bittu** [lebab/lebab#357]
i am unable to convert function prototype methods to arrow functions. It just converts function to class and all the methods to normal methods.

Source:
```js
var CustomEvent = function(type) {
    this._type = type;
    this._target = null;
};

CustomEvent.prototype.getType = function() {
    return this._type;
};
```

Current output:
```js
class CustomEvent {
    constructor(type) {
	this._type = type;
	this._target = null;
    }

    getType() {
	return this._type;
    }
}
```

Expected output:
```js
class CustomEvent {
    constructor(type) {
	this._type = type;
	this._target = null;
    }

    getType = () => {
	return this._type;
    }
}
```

Is there a way i can achieve this?

**Comment by nene** [comment]
This works as designed.

I don't know why you would instead want the other output. Like, in this example code, your version has the downside that getType is treated as a local field (not as a method), so it gets recreated every time a class gets instantiated.

There are some usecases for this, where you want these functions to form closures over some local variables. But IMHO, it's better to be avoided if possible.

Unless there's something in your actual code that this coversion breaks, this sort of thing is out of scope for Lebab.

**Comment by github-nilsson** [comment]
I agree. The initial code would have to look like this
`var CustomEvent = function(type) {
    this._type = type;
    this._target = null;
    this.getType = this.getType.bind(this);
};`
in which case you could argue for the getType arrow function.
