### ISSUE TITLE
What is the use-case for this library ?

### ISSUE THREAD

**Issue by olsonpm** [lebab/lebab#361]
This library showed up in my github "explore repositories" sidebar.  It looks interesting, but why would someone want to do convert es5 to es6/7 ?

**Comment by nene** [comment]
Well, if you have a codebase that's written in ES5 style and you'd like to modernize it. At least that was my initial use case for it. I'm sure people also use it for many other purposes for which it wasn't intended.

But it has been gethering dust now for a while as, well... I personally don't have a need for it. Though I'm sure there's lots of ES5 code out there which people still decide to modernize every now and then.

**Comment by nene** [comment]
I'm closing this issue, as well, it's not really a real problem :)

Feel free to ask more if needed.

**Comment by olsonpm** [comment]
I appreciate you sharing - and sounds good about closing though I think a blurb in the readme explaining why the library was created (preferably by the author) would be helpful to those coming across it for the first time.

**Comment by nene** [comment]
I guess your case of finding it by Github suggestion is rather the odd situation. Frankly never used this feature. Gave it a try to find out... and indeed it suggested me some repositories which were like I-have-no-idea-what-this-is-for-or-why-github-suggests-it-to-me :)

You're also the first one who's ever expressed confusion over the purpose of this. If I get more complaints like this, I'll perhaps act.

**Comment by olsonpm** [comment]
haha yeah devs usually omit use-cases and why they built something unfortunately (in my opinion of course).  There are times where that info is functionally useful rather than only satisfying curiosity.  The other week i was introduced to a lib because my task was to update our project's dependencies.  The library omitted its purpose and I couldn't tell without looking at the code what it was doing - which made it time consuming for me to validate whether updating the dependency worked or broke something.  In this case at least it's obvious what the library is doing.

Anyway thanks for taking time to respond - have a good one :)
